import React from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Download, FileText, FileSpreadsheet } from 'lucide-react';
import { format } from 'date-fns';
import { ExportRecord, mockUsers } from '@/data/mockData';

interface ExportHistoryProps {
  exports: ExportRecord[];
  onDownload: (record: ExportRecord) => void;
}

const ExportHistory: React.FC<ExportHistoryProps> = ({ exports, onDownload }) => {
  const getUser = (userId: string) => mockUsers.find((u) => u.id === userId);

  const getTypeIcon = (type: ExportRecord['type']) => {
    switch (type) {
      case 'as_built_pdf':
        return <FileText className="w-4 h-4 text-destructive" />;
      case 'ce_upload':
      case 'unit_csv':
        return <FileSpreadsheet className="w-4 h-4 text-secondary" />;
    }
  };

  const getTypeLabel = (type: ExportRecord['type']) => {
    switch (type) {
      case 'as_built_pdf':
        return 'As-Built PDF';
      case 'ce_upload':
        return 'CE Upload';
      case 'unit_csv':
        return 'Unit CSV';
    }
  };

  return (
    <div className="space-y-4">
      <h3 className="text-lg font-semibold">Export History</h3>

      <div className="rounded-lg border border-border bg-card">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>File Name</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Date/Time</TableHead>
              <TableHead className="w-20"></TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {exports.length === 0 ? (
              <TableRow>
                <TableCell colSpan={5} className="text-center py-8 text-muted-foreground">
                  No exports generated yet.
                </TableCell>
              </TableRow>
            ) : (
              exports.map((record) => {
                const user = getUser(record.generatedBy);
                return (
                  <TableRow key={record.id}>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        {getTypeIcon(record.type)}
                        <span className="font-medium">{record.fileName}</span>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline">{getTypeLabel(record.type)}</Badge>
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {user?.name || '—'}
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {format(new Date(record.createdAt), 'MMM d, yyyy h:mm a')}
                    </TableCell>
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8"
                        onClick={() => onDownload(record)}
                      >
                        <Download className="w-4 h-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                );
              })
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  );
};

export default ExportHistory;
